spring:
  profiles:
    active: prod

feign:
  client:
    config:
      default:
        logger-level: FULL

logging:
  level:
    com.example: DEBUG
    web: TRACE
    org.springframework.web: TRACE